---
title: "training"
author: "YANG,Fan"
date: "2024-03-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
#导入数据
library(tidyverse)
TD<-read.csv("tidy data.csv")
names(TD)
ggplot(TD,aes(Time,Mass))+
  geom_point()
#筛选所需要的Guppy数据
T1<-filter(TD,Study.Number=="1")
T1

#拟合
nls(Mass~M*(1-(1-(m0/M)^(1/3))*exp(-(a/3)*M^(-1/3)*Time))^3,
    data=T1,
    start=list(m0=0.008,M=0.15,a=0.064))
#将拟合结果储存
fit1_Guppy<-nls(Mass~M*(1-(1-(m0/M)^(1/3))*exp(-(a/3)*M^(-1/3)*Time))^3,
    data=T1,
    start=list(m0=0.008,M=0.15,a=0.064))

pTime_Guppy<-T1[,2]
pMass_Guppy<-0.149248*(1-(1-(0.001771/0.149248)^(1/3))*exp(-(0.072807/3)*0.149248^(-1/3)*pTime_Guppy))^3
pfit1_Guppy<-data.frame(pTime_Guppy,pMass_Guppy)

summary(fit1_Guppy)

names(summary(fit1_Guppy))

summary(fit1_Guppy)$coefficients
#提取拟合结果中的参数
m0_1 <- summary(fit1_Guppy)$coefficients[1]

M_1 <- summary(fit1_Guppy)$coefficients[2]

a_1<-summary(fit1_Guppy)$coefficients[3]
#尝试画拟合线
ggplot(T1,aes(Time,Mass))+
  geom_point(color="green4")+
  geom_function(fun=function(x)M_1*(1-(1-(m0_1/M_1)^(1/3))*exp(-(a_1/3)*M_1^(-1/3)*x))^3)+
  theme_bw()
#生成拟合数据点
Time<-seq(0,90,length.out=1000)
length(Time)

m0all<-rep(m0_1,1000)
length(m0all)

Mall<-rep(M_1,1000)
length(Mall)

aall<-rep(a_1,1000)
length(aall)

Mass<-Mall*(1-(1-(m0all/Mall)^(1/3))*exp(-(aall/3)*Mall^(-1/3)*Time))^3
length(Mass)

dfit1_Guppy<-data.frame(Time,Mass)
#画拟合线1
ggplot(T1, aes(Time, Mass))+
  geom_point(colour="green4")+
  geom_line(data = dfit1_Guppy,colour="red3",size=0.5,linetype="dashed")+
  theme_bw()
#同理画拟合线2
nls(Mass~M2*(1-(1-(m02/M2)^0.25)*exp(-a2*Time/(4*M2^0.25)))^4,
    data=T1,
    start=list(m02=0.008,M2=0.15,a2=0.1))

fit2_Guppy<-nls(Mass~M2*(1-(1-(m02/M2)^0.25)*exp(-a2*Time/(4*M2^0.25)))^4,
    data=T1,
    start=list(m02=0.002601,M2=0.148227,a2=0.119613))

pTime2_Guppy<-T1[,2]
pMass2_Guppy<-0.148227*(1-(1-(0.002601/0.148227)^0.25)*exp(-0.119613*pTime2_Guppy/(4*0.148227^0.25)))^4
pfit2_Guppy<-data.frame(pTime2_Guppy,pMass2_Guppy)


m0_2<-summary(fit2_Guppy)$coefficients[1]

M_2 <- summary(fit2_Guppy)$coefficients[2]

a_2 <- summary(fit2_Guppy)$coefficients[3]

Time2<-seq(0,90,length.out=1000)
length(Time2)

m0all2<-rep(m0_2,1000)
length(m0all)

Mall2<-rep(M_2,1000)
length(Mall2)

aall2<-rep(a_2,1000)
length(aall2)

Mass2<-Mall2*(1-(1-(m0all2/Mall2)^0.25)*exp(-aall2*Time/(4*Mall2^0.25)))^4
length(Mass2)

dfit2_Guppy<-data.frame(Time2,Mass2)

p2<-ggplot()+
  geom_point(data = T1,aes(Time,Mass),colour="#21B14A")+
  geom_line(data = dfit1_Guppy,aes(Time,Mass),colour="#C41425",size=0.5,linetype="dashed")+  #虚线
  geom_line(data = dfit2_Guppy,aes(Time2,Mass2),colour="#0165AD",size=0.8,linetype="dashed")+
  geom_point(data=pfit1_Guppy,aes(pTime_Guppy,pMass_Guppy),color="#C41425",size=2.1)+
  geom_point(data=pfit2_Guppy,aes(pTime2_Guppy,pMass2_Guppy),color="#0165AD",size=1.5)+
  scale_x_continuous(limits = c(0,90),breaks = seq(0,90,10),sec.axis=dup_axis(
      breaks = seq(0,90,10),
      name = NULL))+ #设置刻度线曲线，设置刻度线间隔，加顶部刻度线,复制主刻度线间隔但是次刻度线名为NULL
  scale_y_continuous(limits = c(0,0.16),breaks = seq(0,0.16,0.02),sec.axis = dup_axis(
      breaks = seq(0,0.16,0.02),
      name = NULL))+ #设置刻度线曲线，设置刻度线间隔，加右侧刻度线
  theme_bw()+ #去背景
  ggtitle("Guppy")+
  theme(panel.grid=element_blank(),
        plot.title = element_text(hjust = 0.5,size=12),    #去网格线+标题居中+字体大小
        axis.title.x =element_text(size=10,face = "bold"),       #刻度线标签字体大小
        axis.title.y=element_text(size=10,face = "bold"),
        axis.ticks.length=unit(-0.1, "cm"),         #刻度线向内0.1cm
        axis.text=element_text(size=10)) +
  labs(x = "Time (days)",y = "Mass (g)")
  

#筛选所需要的Hen数据
T3<-filter(TD,Study.Number=="3")

#拟合
nls(Mass~M*(1-(1-(m0/M)^(1/3))*exp(-(a/3)*M^(-1/3)*Time))^3,
    data=T3,
    start=list(m0=43,M=2100,a=0.67))
#将拟合结果储存
fit1_Hen<-nls(Mass~M*(1-(1-(m0/M)^(1/3))*exp(-(a/3)*M^(-1/3)*Time))^3,
    data=T3,
    start=list(m0=43,M=2100,a=0.67))

pTime_Hen<-T3[,2]
pMass_Hen<-2104.7307*(1-(1-(89.9730/2104.7307)^(1/3))*exp(-(0.5714/3)*2104.7307^(-1/3)*pTime_Hen))^3
pfit1_Hen<-data.frame(pTime_Hen,pMass_Hen)


#提取拟合结果中的参数
m0_1 <- summary(fit1_Hen)$coefficients[1]

M_1 <- summary(fit1_Hen)$coefficients[2]

a_1<-summary(fit1_Hen)$coefficients[3]

#生成拟合数据点
Time<-seq(0,400,length.out=1000)
length(Time)

m0all<-rep(m0_1,1000)
length(m0all)

Mall<-rep(M_1,1000)
length(Mall)

aall<-rep(a_1,1000)
length(aall)

Mass<-Mall*(1-(1-(m0all/Mall)^(1/3))*exp(-(aall/3)*Mall^(-1/3)*Time))^3
length(Mass)

dfit1_Hen<-data.frame(Time,Mass)
#画拟合线1
ggplot(T3, aes(Time, Mass))+
  geom_point(colour="green4")+
  geom_line(data = dfit1_Hen,colour="red3",size=0.5,linetype="dashed")+
  theme_bw()
#同理画拟合线2
nls(Mass~M2*(1-(1-(m02/M2)^0.25)*exp(-a2*Time/(4*M2^0.25)))^4,
    data=T3,
    start=list(m02=43,M2=2100,a2=0.47))

fit2_Hen<-nls(Mass~M2*(1-(1-(m02/M2)^0.25)*exp(-a2*Time/(4*M2^0.25)))^4,
    data=T3,
    start=list(m02=43,M2=2100,a2=0.47))

pTime2_Hen<-T3[,2]
pMass2_Hen<-2095.8529*(1-(1-(96.9720/2095.8529)^0.25)*exp(-0.4241*pTime2_Hen/(4*2095.8529^0.25)))^4
pfit2_Hen<-data.frame(pTime2_Hen,pMass2_Hen)


m0_2<-summary(fit2_Hen)$coefficients[1]

M_2 <- summary(fit2_Hen)$coefficients[2]

a_2 <- summary(fit2_Hen)$coefficients[3]

Time2<-seq(0,400,length.out=1000)
length(Time2)

m0all2<-rep(m0_2,1000)
length(m0all)

Mall2<-rep(M_2,1000)
length(Mall2)

aall2<-rep(a_2,1000)
length(aall2)

Mass2<-Mall2*(1-(1-(m0all2/Mall2)^0.25)*exp(-aall2*Time/(4*Mall2^0.25)))^4
length(Mass2)

dfit2_Hen<-data.frame(Time2,Mass2)

p3<-ggplot()+
  geom_point(data = T3,aes(Time,Mass),colour="#21B14A")+
  geom_line(data = dfit1_Hen,aes(Time,Mass),colour="#C41425",size=0.5,linetype="dashed")+  #虚线
  geom_line(data = dfit2_Hen,aes(Time2,Mass2),colour="#0165AD",size=0.8,linetype="dashed")+
  geom_point(data=pfit1_Hen,aes(pTime_Hen,pMass_Hen),color="#C41425",size=2.1)+
  geom_point(data=pfit2_Hen,aes(pTime2_Hen,pMass2_Hen),color="#0165AD",size=1.5)+
  scale_x_continuous(limits = c(0,400),breaks = seq(0,400,50),sec.axis=dup_axis(
      breaks = seq(0,400,50),
      name = NULL))+ #设置刻度线曲线，设置刻度线间隔，加顶部刻度线,复制主刻度线间隔但是次刻度线名为NULL
  scale_y_continuous(limits = c(0,2500),breaks = seq(0,2500,500),sec.axis = dup_axis(
      breaks = seq(0,2500,500),
      name = NULL))+ #设置刻度线曲线，设置刻度线间隔，加右侧刻度线
  theme_bw()+ #去背景
  ggtitle("Hen")+
  theme(panel.grid=element_blank(),
        plot.title = element_text(hjust = 0.5,size=12),    #去网格线+标题居中+字体大小
        axis.title.x =element_text(size=10,face = "bold"),       #刻度线标签字体大小
        axis.title.y=element_text(size=10,face = "bold"),
        axis.ticks.length=unit(-0.1, "cm"),         #刻度线向内0.1cm
        axis.text=element_text(size=10)) +
  labs(x = "Time (days)",y = "Mass (g)")

#筛选所需要的Cow数据
T12<-filter(TD,Study.Number=="12")

#拟合
nls(Mass~M*(1-(1-(m0/M)^(1/3))*exp(-(a/3)*M^(-1/3)*Time))^3,
    data=T12,
    start=list(m0=33300,M=442000,a=0.62))
#将拟合结果储存
fit1_Cow<-nls(Mass~M*(1-(1-(m0/M)^(1/3))*exp(-(a/3)*M^(-1/3)*Time))^3,
    data=T12,
    start=list(m0=33300,M=442000,a=0.62))

pTime_Cow<-T12[,2]
pMass_Cow<-429600*(1-(1-(30280/429600)^(1/3))*exp(-(0.6152/3)*429600^(-1/3)*pTime_Cow))^3/1000
pfit1_Cow<-data.frame(pTime_Cow,pMass_Cow)


#提取拟合结果中的参数
m0_1 <- summary(fit1_Cow)$coefficients[1]

M_1 <- summary(fit1_Cow)$coefficients[2]

a_1<-summary(fit1_Cow)$coefficients[3]

#生成拟合数据点
Time<-seq(0,2500,length.out=1000)
length(Time)

m0all<-rep(m0_1,1000)
length(m0all)

Mall<-rep(M_1,1000)
length(Mall)

aall<-rep(a_1,1000)
length(aall)

Mass<-Mall*(1-(1-(m0all/Mall)^(1/3))*exp(-(aall/3)*Mall^(-1/3)*Time))^3/1000
length(Mass)

dfit1_Cow<-data.frame(Time,Mass)

#同理画拟合线2
nls(Mass~M2*(1-(1-(m02/M2)^0.25)*exp(-a2*Time/(4*M2^0.25)))^4,
    data=T12,
    start=list(m02=33300,M2=442000,a2=0.28))

fit2_Cow<-nls(Mass~M2*(1-(1-(m02/M2)^0.25)*exp(-a2*Time/(4*M2^0.25)))^4,
    data=T12,
    start=list(m02=33300,M2=442000,a2=0.28))

pTime2_Cow<-T12[,2]
pMass2_Cow<-428300*(1-(1-(32720/428300)^0.25)*exp(-0.2904*pTime2_Cow/(4*428300^0.25)))^4/1000
pfit2_Cow<-data.frame(pTime2_Cow,pMass2_Cow)


m0_2<-summary(fit2_Cow)$coefficients[1]

M_2 <- summary(fit2_Cow)$coefficients[2]

a_2 <- summary(fit2_Cow)$coefficients[3]

Time2<-seq(0,2500,length.out=1000)
length(Time2)

m0all2<-rep(m0_2,1000)
length(m0all)

Mall2<-rep(M_2,1000)
length(Mall2)

aall2<-rep(a_2,1000)
length(aall2)

Mass2<-Mall2*(1-(1-(m0all2/Mall2)^0.25)*exp(-aall2*Time/(4*Mall2^0.25)))^4/1000
length(Mass2)

dfit2_Cow<-data.frame(Time2,Mass2)

p1<-ggplot()+
  geom_point(data = T12,aes(Time,Mass/1000),colour="#21B14A")+
  geom_line(data = dfit1_Cow,aes(Time,Mass),colour="#C41425",size=0.5,linetype="dashed")+  #虚线
  geom_line(data = dfit2_Cow,aes(Time2,Mass2),colour="#0165AD",size=0.8,linetype="dashed")+
  geom_point(data=pfit1_Cow,aes(pTime_Cow,pMass_Cow),color="#C41425",size=2.1)+
  geom_point(data=pfit2_Cow,aes(pTime2_Cow,pMass2_Cow),color="#0165AD",size=1.5)+
  scale_x_continuous(limits = c(0,2500),breaks = seq(0,2500,500),sec.axis=dup_axis(
      breaks = seq(0,2500,500),
      name = NULL))+ #设置刻度线曲线，设置刻度线间隔，加顶部刻度线,复制主刻度线间隔但是次刻度线名为NULL
  scale_y_continuous(limits = c(0,450),breaks = seq(0,450,50),sec.axis = dup_axis(
      breaks = seq(0,450,50),
      name = NULL))+ #设置刻度线曲线，设置刻度线间隔，加右侧刻度线
  theme_bw()+ #去背景
  ggtitle("Cow")+
  theme(panel.grid=element_blank(),
        plot.title = element_text(hjust = 0.5,size=12),    #去网格线+标题居中+字体大小
        axis.title.x =element_text(size=10,face = "bold"),       #刻度线标签字体大小
        axis.title.y=element_text(size=10,face = "bold"),
        axis.ticks.length=unit(-0.1, "cm"),         #刻度线向内0.1cm
        axis.text=element_text(size=10)) +
  labs(x = "Time (days)",y = "Mass (kg)")

#图d数据提取与构建
#Guppy数据提取
Mass_Guppy<-T1[3]
#分别提取"a=3/4"与"a=2/3"时的r值，即"dimensionless mass ratio"
Guppy_x1<-(Mass_Guppy/0.15)^0.25
Guppy_x2<-(Mass_Guppy/0.15)^(1/3)  
Time_Guppy=T1[2]
#分别提取"a=3/4"与"a=2/3"时的t值，即"dimensionless time"
Guppy_y1<--log(((1-(0.008/0.15)^0.25)*exp(-Time_Guppy*0.1/(4*0.15^0.25))))
Guppy_y2<--log(((1-(0.008/0.15)^(1/3))*exp(-Time_Guppy*0.064/(3*0.15^(1/3)))))
#将两个数据框合并成一个并命名
Guppy_1<-data.frame(cbind(Guppy_x1,Guppy_y1))
colnames(Guppy_1)<-c("dimensionless mass ratio","dimensionless time")
Guppy_2<-data.frame(cbind(Guppy_x2,Guppy_y2))
#将两个数据框合并成一个并命名
colnames(Guppy_2)<-c("dimensionless mass ratio","dimensionless time")
d_Guppy<-data.frame(rbind(Guppy_1,Guppy_2))
#将两个数据框合并成一个并增添一个用于分类的向量
Guppy_end<-mutate(d_Guppy,name="Guppy")
#Hen数据提取同上
Mass_Hen<-T3[3]
Hen_x1<-(Mass_Hen/2100)^0.25
Hen_x2<-(Mass_Hen/2100)^(1/3)  
Time_Hen=T3[2]
Hen_y1<--log(((1-(43/2100)^0.25)*exp(-Time_Hen*0.47/(4*2100^0.25))))
Hen_y2<--log(((1-(43/2100)^(1/3))*exp(-Time_Hen*0.67/(3*2100^(1/3)))))
Hen_1<-data.frame(cbind(Hen_x1,Hen_y1))
colnames(Hen_1)<-c("dimensionless mass ratio","dimensionless time")
Hen_2<-data.frame(cbind(Hen_x2,Hen_y2))
colnames(Hen_2)<-c("dimensionless mass ratio","dimensionless time")
d_Hen<-data.frame(rbind(Hen_1,Hen_2))
Hen_end<-mutate(d_Hen,name="Hen")
#Cow数据提取同上
Mass_Cow<-T12[3]
Cow_x1<-(Mass_Cow/442000)^0.25
Cow_x2<-(Mass_Cow/442000)^(1/3)  
Time_Cow=T12[2]
Cow_y1<--log(((1-(33300/442000)^0.25)*exp(-Time_Cow*0.28/(4*442000^0.25))))
Cow_y2<--log(((1-(33300/442000)^(1/3))*exp(-Time_Cow*0.62/(3*442000^(1/3)))))
Cow_1<-data.frame(cbind(Cow_x1,Cow_y1))
colnames(Cow_1)<-c("dimensionless mass ratio","dimensionless time")
Cow_2<-data.frame(cbind(Cow_x2,Cow_y2))
colnames(Cow_2)<-c("dimensionless mass ratio","dimensionless time")
d_Cow<-data.frame(rbind(Cow_1,Cow_2))
Cow_end<-mutate(d_Cow,name="Cow")
#将三个数据框合并绘图
all<-data.frame(rbind(Guppy_end,Hen_end,Cow_end))


p4<-ggplot(all,aes(dimensionless.time,dimensionless.mass.ratio,color=name))+
  geom_point()+
  #绘制拟合线
  geom_function(fun=function(dimensionless.time)1-exp(-dimensionless.time),color="black",lty=3)+
  scale_x_continuous(limits = c(0,8),breaks = seq(0,8,1),sec.axis=dup_axis(
      breaks = seq(0,8,1),
      name = NULL))+ #设置刻度线曲线，设置刻度线间隔，加顶部刻度线,复制主刻度线间隔但是次刻度线名为NULL
  scale_y_continuous(limits = c(0,1.2),breaks = seq(0,1.2,0.2),sec.axis = dup_axis(
      breaks = seq(0,1.2,0.2),
      name = NULL))+ #设置刻度线曲线，设置刻度线间隔，加右侧刻度线
  theme_bw()+ #去背景
  ggtitle("Scaling Collapse")+
  theme(panel.grid=element_blank(),
        plot.title = element_text(hjust = 0.5,size=12),    #去网格线+标题居中+字体大小
        axis.title.x =element_text(size=10,face = "bold"),       #刻度线标签字体大小
        axis.title.y=element_text(size=10,face = "bold"),
        axis.ticks.length=unit(-0.1, "cm"),         #刻度线向内0.1cm
        axis.text=element_text(size=10),
        legend.position = c(1,0),  #调整图例位置
        legend.justification = c(1,0),
        legend.background = element_blank()) +
  labs(x = "dimensionless.time",y = "dimensionless.mass.ratio")
library(cowplot)
 cowplot::plot_grid(p1,p2,p3,p4,ncol=2,labels=c("a","b","c","d")) 
 ggsave("Growth curves.png",width=771/90,height=562/90,dpi=900)
 ggsave("Growth curves.pdf",width=771/90,height=562/90,dpi=900)

 #图中a-c显示的是三种生物的生长曲线，绿色是原始数值，蓝色和红色分别为两种不同的拟合方式，其方程和初始参数分别来自文献:Modelling universality and scaling/A general model for ontogenetic growth。图d是来自三个物种的通用生长曲线。
  
  
  
  
  
  
  
  


```

